defaults:
  - config: cgd

# ETC
seed: 42
num_workers: 8
wandb_logger: true
project: GLD2021
lr_finder: false
checkpoint_dir: /root/kaggle/google-retrieval/pl_output
gpus: [0, 1, 2]
precision: 16

# Dataset
data_root: /shared/lorenzo/data-gld
split_df_root: /root/kaggle/google-retrieval/split
img_size: 384
num_classes: 81313
aug: true
fold_no: 0

# Training
max_epochs: 25
batch_size: 32
lr: 1e-3
lr_scheduler: false
optimizer: adamw
es_patience: null

# saved model
weight_path: /root/kaggle/google-retrieval/pl_output/resnet50-epoch=23-fold0-val_loss=3.8455.ckpt
output_dir: /root/kaggle/google-retrieval/weight